### ISSUE TITLE
How to watch changes files on device in real-time?

### ISSUE THREAD

**Issue by Symfomany** [NativeScript/nativescript-dev-webpack#43] opened 2016-12-24 13:08 UTC
When I run script _npm run start-android-bundle_ & after i modify my app.component.html ,  

My App no reboot on my device for previsualtion  but in my console, there is several changes:

Transferring project files...
Successfully transferred all files.
Applying changes...

An idea please?

Thx for advance!

**Comment by Symfomany** [comment] 2016-12-26 07:26
Hye,

Existing an Deboger on VSCOde synchronize with Webpack?

My launch.json configuration for android sync has failed :( Do you have some examples please?

Thx!!

**Comment by hdeshev** [comment] 2016-12-27 07:49
Duplicate of #37

**Closed by hdeshev** 2016-12-27 07:49 UTC
