### ISSUE TITLE
nativescript-telerik-ui not supporting AoT compilation

### ISSUE THREAD

**Issue by newapx** [NativeScript/nativescript-dev-webpack#31] opened 2016-12-06 11:53 UTC
Use version 0.2.11
After the command `npm run start-android-bundle`  in step `webpack --config = webpack.android.js --progress` out error 
`Error: Unexpected value 'SIDEDRAWER_DIRECTIVES' declared by the module 'AppModule'`  
in `\node_modules\@angular\compiler\bundles\compiler.umd.js:14722:29`

Use Angular, AppModule is main and one application module.
SIDEDRAWER_DIRECTIVES from plugins `nativescript-telerik-ui`

**Comment by hdeshev** [comment] 2016-12-09 13:09
I haven't seen this error before. Could you post your project somewhere on GitHub, so I can reproduce it on my end?

**Comment by newapx** [comment] 2016-12-10 14:22
Here is a link to the  project (https://github.com/newapx/nativescipt.sidedraw-webpack)

**Comment by hdeshev** [comment] 2016-12-12 10:03
Thanks for the project! It turns out the nativescript-telerik-ui package doesn't ship component metadata yet (Hence no AoT support). I opened an issue on their tracker.

Until we get this fixed, it should be possible to use the dynamic platform without the ng-tools webpack loader, but I would recommend against that, since it will ship the entire compiler codebase in the app.

Ping @VladimirAmiorkov

**Comment by imaginationcoder** [comment] 2017-01-10 19:33
Same here:
`ERROR in Unexpected value 'SIDEDRAWER_DIRECTIVES' declared by the module 'AppModule'`
My 'app.module.ts' includes below
`import {SIDEDRAWER_DIRECTIVES} from "nativescript-telerik-ui/sidedrawer/angular";`
and 
@NgModule 
```
declarations: [
        SIDEDRAWER_DIRECTIVES,
        AppComponent 
    ] 
```
Can any one please help me here to resolve the issue when using **'nativescript-dev-webpack'.**
Everything is working fine without **webpack** usage

**Comment by VladimirAmiorkov** [comment] 2017-01-11 10:51
@imaginationcoder The current 1.5.1 version of the nativescript-telerik-ui plugin does not support AoT compilation which is by default enabled in nativescript-dev-webpack. We are already working on resolving this issue and we are expecting to release a version 1.6.1 which should include the mentioned support for AoT compilation. We apologize for any inconvenience that this might by causing.

**Comment by imaginationcoder** [comment] 2017-01-11 18:00
@VladimirAmiorkov  thank you for your quick reply.. is there any chance to me expect the release date of version 1.6.1?

**Comment by VladimirAmiorkov** [comment] 2017-01-11 19:21
@imaginationcoder The 1.6.1 release is planned to be out in a week after the 1.6.0 release which is doe to be released in two weeks.

**Comment by dunqan** [comment] 2017-02-07 10:30
@VladimirAmiorkov sorry for bugging you, but are there still chanes that mentioned 1.6.1 version will be released soon? Thanks!

**Comment by VladimirAmiorkov** [comment] 2017-02-07 15:54
Hi @dunqan,

The 1.6.1 is currently being worked on and will be available soon, more information about this can be found in [this](http://www.telerik.com/forums/nativescript-telerik-ui-not-supporting-aot-compilation) thread.

**Comment by triniwiz** [comment] 2017-02-26 14:38
I can confirm this works now 👍

**Comment by nraboy** [comment] 2017-03-02 01:01
I'm getting the following error now:

```
ERROR in Type RadSideDrawerComponent is part of the declarations of 2 modules: NativeScriptUISideDrawerModule and AppModule
```

**Comment by VladimirAmiorkov** [comment] 2017-03-02 06:36
@nraboy Make sure to remove the sidedrawer import from the declarations of your AppModule.

**Comment by nraboy** [comment] 2017-03-04 23:11
Yes I did.  The error is happening after I had done this.  This is what my file looks like:

```
import { NgModule, NO_ERRORS_SCHEMA } from "@angular/core";
import { NativeScriptModule } from "nativescript-angular/nativescript.module";
import { NativeScriptHttpModule } from "nativescript-angular/http";
import { NativeScriptUISideDrawerModule } from "nativescript-telerik-ui-pro/sidedrawer/angular";
import { NativeScriptUIListViewModule } from "nativescript-telerik-ui-pro/listview/angular";
import { ModalDialogService } from "nativescript-angular/modal-dialog";
import { AppRoutingModule, Components } from "./app.routing";
import { AppComponent } from "./app.component";
import { registerElement } from 'nativescript-angular/element-registry';

import { IfAndroidDirective, IfIosDirective } from "./directives/if-platform.directive";

import { ZoneProvider } from "./providers/zone.provider";
import { CloudFlareProvider } from "./providers/cloudflare.provider";
import { GoogleProvider } from "./providers/google.provider";

import { ZonesModal } from "./modals/zones/zones.modal";
import { GenericModal } from "./modals/generic/generic.modal";

registerElement("CardView", () => require("nativescript-cardview").CardView);
registerElement("Fab", () => require("nativescript-floatingactionbutton").Fab);
registerElement("CheckBox", () => require("nativescript-checkbox").CheckBox);

@NgModule({
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        NativeScriptHttpModule,
        NativeScriptUISideDrawerModule,
        NativeScriptUIListViewModule,
        AppRoutingModule
    ],
    declarations: [
        AppComponent,
        IfAndroidDirective,
        IfIosDirective,
        ...Components,
        ZonesModal,
        GenericModal
    ],
    entryComponents: [ZonesModal, GenericModal],
    providers: [ModalDialogService, ZoneProvider, CloudFlareProvider, GoogleProvider],
    schemas: [
        NO_ERRORS_SCHEMA
    ]
})
export class AppModule { }
```

As you can see nothing stands out.  Then I try to use my `RidSideDrawerComponent` as defined in the documentation.

Best,

**Comment by VladimirAmiorkov** [comment] 2017-03-05 08:16
@nraboy Are you sure no other component in your app is importing the from `"nativescript-telerik-ui-pro/sidedrawer/angular"` maybe the `AppComponent `or `...Components`. Can you send a sample of the project so I can take a look at it?

**Comment by nraboy** [comment] 2017-03-11 00:55
I have this in one of my components:

```
import { Component, ViewChild, ViewContainerRef, OnInit } from "@angular/core";
import { Http } from "@angular/http";
import { RouterExtensions } from "nativescript-angular/router";
import { ListViewEventData, RadListView } from "nativescript-telerik-ui-pro/listview";
import { RadSideDrawerComponent, SideDrawerType } from "nativescript-telerik-ui-pro/sidedrawer/angular";
import { ModalDialogService } from "nativescript-angular/directives/dialogs";
import { View } from 'ui/core/view';
import * as Utils from "utils/utils";
import * as Dialogs from "ui/dialogs";
import * as FrameModule from "ui/frame";
import * as ApplicationSettings from "application-settings";
import { Configuration } from "../../config";
import * as Toast from 'nativescript-toast';
import "rxjs/Rx";
@Component({
    selector: "secure",
    templateUrl: "./components/secure/secure.component.html",
    styleUrls: ["./components/secure/secure.component.css"]
})
export class SecureComponent implements OnInit {
    private drawer: SideDrawerType;
    @ViewChild(RadSideDrawerComponent)
    public drawerComponent: RadSideDrawerComponent;
```

Without the import, the definitions will throw errors.

**Comment by VladimirAmiorkov** [comment] 2017-03-11 12:47
This all looks fine, can you wrap a test project and send it to me, without being able to reproduce this issue on my end I cannot help you further.

**Comment by imaginationcoder** [comment] 2017-03-19 06:46
@VladimirAmiorkov
**Now working fine for me  thank you for version 1.6.1** 
Nativescript: 2.5.2 | tns-ios: 2.5.0  | "tns-core-modules": "^2.5.1"

```
and my app.module.ts contains

// --- The built-in 'nativescript-telerik-ui' modules
import { NativeScriptUISideDrawerModule } from "nativescript-telerik-ui/sidedrawer/angular";
import { NativeScriptUIListViewModule } from "nativescript-telerik-ui/listview/angular";

@NgModule({
    declarations: [
      ....
    ],
    bootstrap: [
        AppComponent
    ],
    imports: [
        NativeScriptModule,
        NativeScriptUIListViewModule,
       NativeScriptUISideDrawerModule,
      ......
    ],
    .....
 
```

**Comment by Salahudeen** [comment] 2017-04-13 17:56
I am also running into the same issue. which library version are you referring to as 1.6.1 ? 
The nativescript-dev-webpack latest release is 0.3.7.

**Comment by VladimirAmiorkov** [comment] 2017-04-13 19:23
@Salahudeen Did you make sure to clean the project (delete node_modules, platforms and maybe the npm cache)

**Comment by Salahudeen** [comment] 2017-04-13 19:55
Tried the same now, but no luck. The issue still persists. Some more points on my project setup.

1. I am using NathanWalkers angular seed advanced project
2. The regular build successfully passes, but the AOT build is where this error shows up.

ERROR in Type RadSideDrawerComponent in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts is part of the declarations of 2 modules: NativeScriptUISideDrawerModule in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts and SideNavModule in nativescript/app/app/shared/side-nav/side-nav.module.ts! Please consider moving RadSideDrawerComponent in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts to a higher module that imports NativeScriptUISideDrawerModule in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts and SideNavModule in nativescript/app/app/shared/side-nav/side-nav.module.ts. You can also create a new NgModule that exports and includes RadSideDrawerComponent in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts then import that NgModule in NativeScriptUISideDrawerModule in nativescript/node_modules/nativescript-telerik-ui-pro/sidedrawer/angular/side-drawer-directives.d.ts and SideNavModule in nativescript/app/app/shared/side-nav/side-nav.module.ts.

**Comment by VladimirAmiorkov** [comment] 2017-04-13 21:23
Did you import the correct ngModule like @imaginationcoder posted earlier? If you can share some of your app implementation I can take a look at it, like the bootstrap component etc.

**Comment by Salahudeen** [comment] 2017-04-14 04:21
Here is the code components. Thanks VladimirAmiorkov for taking time out to resolve my issue.

**component,module.ts**

`
// this import should be first in order to load some required settings (like globals and reflect-metadata)
import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { NativeScriptUIListViewModule } from 'nativescript-telerik-ui-pro/listview/angular';
import { NativeScriptUIDataFormModule } from 'nativescript-telerik-ui-pro/dataform/angular';
import { NativeScriptUIChartModule } from 'nativescript-telerik-ui-pro/chart/angular';

// nativescript
import { NativeScriptFormsModule } from 'nativescript-angular/forms';
import { NativeScriptHttpModule } from 'nativescript-angular/http';
import { NativeScriptRouterModule } from 'nativescript-angular/router';
import { Http } from '@angular/http';

// angular
import { NgModule, CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA } from '@angular/core';

// libs
import { TranslateLoader } from '@ngx-translate/core';
import { TranslateHttpLoader } from '@ngx-translate/http-loader';

// app
import { AppComponent } from './app/components/app.component';
import { APP_COMPONENTS } from './app/components';

import { routes } from './app/components/app.routes';

// feature modules
import { CoreModule } from './app/shared/core/core.module';
import { AnalyticsModule } from './app/shared/analytics/analytics.module';
import { MultilingualModule, translateLoaderFactory } from './app/shared/i18n/multilingual.module';
import { SideNavModule } from './app/shared/side-nav/side-nav.module';


import { AuthGuard } from './app/auth-guard.service';
import { ConsoleService, ConsoleTarget, LogLevel } from './app/shared/core/index';

// intermediate component module
// helps encapsulate custom native modules in with the components
// note: couple ways this could be done, just one option presented here...
@NgModule({
  imports: [
    NativeScriptModule,
    NativeScriptUIListViewModule,
    NativeScriptUIChartModule,
    NativeScriptUIDataFormModule,
    NativeScriptFormsModule,
    NativeScriptHttpModule,
    NativeScriptRouterModule,
    AnalyticsModule,
    CoreModule,
    MultilingualModule.forRoot([{
      provide: TranslateLoader,
      deps: [Http],
      useFactory: (translateLoaderFactory)
    }]),
    SideNavModule,
    SampleModule,
    ProcessCertificationModule,
  ],
  declarations: [
    ...APP_COMPONENTS,
  ],
  schemas: [
    NO_ERRORS_SCHEMA,
    CUSTOM_ELEMENTS_SCHEMA
  ],
  exports: [
    NativeScriptModule,
    NativeScriptFormsModule,
    NativeScriptHttpModule,
    NativeScriptRouterModule,
    MultilingualModule,
    SideNavModule,
   ...
  ],
  providers: [AuthGuard]
})
export class ComponentsModule { }
`
**native,module.ts**

`// nativescript
import {
  NativeScriptRouterModule,
  RouterExtensions as TNSRouterExtensions
} from 'nativescript-angular';

// angular
import { NgModule, CUSTOM_ELEMENTS_SCHEMA, NO_ERRORS_SCHEMA } from '@angular/core';
import { ComponentsModule } from './components.module';

// libs
import { StoreModule } from '@ngrx/store';
import { EffectsModule } from '@ngrx/effects';

import { AppComponent } from './app/components/app.component';
import { routes } from './app/components/app.routes';

// {N} custom app specific
import { WindowNative, NSAppService } from './mobile/core/index';
import { NS_ANALYTICS_PROVIDERS } from './mobile/analytics/index';


@NgModule({
    ComponentsModule,
    NativeScriptRouterModule.forRoot(<any>routes),
    StoreModule.provideStore(AppReducer),
    EffectsModule.run(MultilingualEffects),
    EffectsModule.run(NameListEffects)
  ],
  providers: [
    NS_ANALYTICS_PROVIDERS,
    { provide: RouterExtensions, useClass: TNSRouterExtensions },
    { provide: AppService, useClass: NSAppService },
  ],
  schemas: [
    NO_ERRORS_SCHEMA,
    CUSTOM_ELEMENTS_SCHEMA
  ],
  bootstrap: [AppComponent]
})
export class NativeModule { }
`
**side-nav.module.ts**

`import { NgModule } from '@angular/core';

import { NativeScriptModule } from 'nativescript-angular/nativescript.module';
import { SIDEDRAWER_DIRECTIVES } from 'nativescript-telerik-ui-pro/sidedrawer/angular';

import { SideDrawerPageComponent } from './side-drawer-page';
import { BorderlessBtnDirective } from './borderless-btn.directive';

@NgModule({
  imports: [
    NativeScriptModule,
  ],
  declarations: [
    SIDEDRAWER_DIRECTIVES,
    SideDrawerPageComponent,
    BorderlessBtnDirective
  ],
  exports: [
    SideDrawerPageComponent,
    BorderlessBtnDirective,
    // SIDEDRAWER_DIRECTIVES,
  ]
})
export class SideNavModule {

}
`

**Comment by VladimirAmiorkov** [comment] 2017-04-14 14:09
@Salahudeen you are welcome if you have any questions, bug reports or feature requests for the _nativescript-telerik-ui plugin_ you can stop by our won feedback repo here: https://github.com/telerik/nativescript-ui-feedback/issues

**Comment by VladimirAmiorkov** [comment] 2017-04-14 14:11
Closing this issue, AoT should work with [nativescript-telerik-ui](https://www.npmjs.com/package/nativescript-telerik-ui) and [nativescript-telerik-ui-pro](https://www.npmjs.com/package/nativescript-telerik-ui-pro) plugins **version above 1.6.0**

**Comment by nraboy** [comment] 2017-04-14 15:47
> Closing this issue, AoT should work with nativescript-telerik-ui and nativescript-telerik-ui-pro plugins version 1.6.1 or above

@VladimirAmiorkov Still doesn't work for me, so I am not sure why you are closing this.

**Comment by VladimirAmiorkov** [comment] 2017-04-14 15:56
@nraboy Can you send me a working project that reproduces this issue as from all of my testing with the code snippets and the discussion with other in this thread after correctly importing the `NgModule ` for the corresponding ui component from the ^1.6.1 version of the nativescript-telerik-ui plugin, AoT is executed without errors? 

You can find information on how to bootstrap your project so that AoT is supported by for the nativescript-telerik-ui plugin in our documentation [here](http://docs.telerik.com/devtools/nativescript-ui/Controls/Angular/getting-started#using-the-ngmodule-of-the-plugins-ui-components).

We have reopened the issue and require more information from anyone experiencing such issues.

**Comment by nraboy** [comment] 2017-04-17 15:49
Just to follow up here.

I've upgraded from CLI 2.5.2 to 2.5.4 and all my problems regarding UI have been resolved.  No idea why, but I'll take it :-)

**Comment by VladimirAmiorkov** [comment] 2017-04-17 15:57
@nraboy Hmm I will take a closer look at that combination, thank you for the information.

**Comment by kvindasAB** [comment] 2017-04-20 15:00
Hello Guys,
Once I changed from constant to module I get the following issue:

Unexpected module 'NativeScriptUISideDrawerModule in /../myproject/node_modules/nativescript-telerik-ui/sidedrawer/angular/side-drawer-directives.d.ts' declared by the module 'AppModule in /.../myproject/app/app.module.ts'

**Closed** 2017-04-26 07:48 UTC
