### ISSUE TITLE
--bundle ruins css

### ISSUE THREAD

**Issue by laimonas** [NativeScript/nativescript-dev-webpack#378] opened 2017-12-22 22:17 UTC
Created new project --ng with angular 5.
Added npm install --save-dev nativescript-dev-webpack
running tns run android everything is ok
running tns run android --bundle listview has no styles.

**Comment by berchik** [comment] 2017-12-23 11:07
This is probably because 
`@import '~nativescript-theme-core/css/core.light.css'` (or similar) in your app.css is not bundled with webpack. I have the same issue.

**Comment by laimonas** [comment] 2017-12-23 11:10
@berchik do you found solution how to solve this?

**Comment by berchik** [comment] 2017-12-23 11:18
One way would of course be to copy manually the android/ios css files from `/node_modules/nativescript-theme-core/css/` to your app/css, but this is quite dirty. I’m trying to look into webpack.config.js but no success yet.

**Comment by milansar** [comment] 2017-12-24 04:43
Have same problem as mentioned by @berchik , after upgrading and following upgrade document changed @import 'nativescript-theme-core/css/core.light.css' to @import '~nativescript-theme-core/css/core.light.css' in app.css.  after bundling app all styles defined in theme core does not apply so it appears that theme core is not copied as it use to be

**Comment by NickIliev** [comment] 2017-12-26 13:40
@berchik @laimonas @milansar confirming this as a bug reproducible only when bundling on Windows.

Steps to reproduce:
- use [this demo application](https://github.com/NickIliev/NS-Issues/tree/master/nativescript-dev-webpack/issue_378)
- CLI build with `tns run android` applies the nativescript theme` from `app.css` as expected
- Bundling with Webpack is not applying the theme styles

Reproducible only on Windows - everything works as expected on Mac (@berchik @laimonas @milansar can you confirm that you are building in Windows environment)

**Comment by laimonas** [comment] 2017-12-26 15:01
@NickIliev yes i'm using windows 10.

**Comment by berchik** [comment] 2017-12-26 15:16
@NickIliev yes the issue is on win10. 
Moving it to OSX the style is applied correctly, but the app is frozen, not sure yet why. 
So I can't comment on using --env.aot/snapshot/uglify for now.

**Comment by milansar** [comment] 2017-12-27 06:49
@NickIliev yes i'm using windows 10

**Comment by behi1ty** [comment] 2017-12-27 16:26
i'm using windows 10 and not set app.css :"@import '~nativescript-theme-core/css/core.light.css';"  after use "tns run android --bundle" but use "tns run android" that is ok!

**Comment by AmithRamesh** [comment] 2017-12-28 07:09
I am facing the same issue on Mac os X as well. The theme core styles are not being applied with 'tns run android --bundle'. Not tried ios build with webpack yet. But 'tns run android' works fine.

**Comment by sis0k0** [comment] 2017-12-29 14:24
Hey, everyone. You can apply that fix https://github.com/NativeScript/nativescript-dev-webpack/pull/385/commits/b1d3bcbd55d4185c677dc6e20ac018aa8305d62e manually in your webpack configurations until #385 is merged and released.

**Comment by berchik** [comment] 2017-12-29 17:19
Thanks Stanimira, 

For win10 I can confirm “~” is resolved correctly as the path relative to node_modules. 
However “~/” is not resolved correctly, but using “./” in app.css instead is ok.

--env.uglify is working too 
--env.aot fails

**Comment by AmithRamesh** [comment] 2018-01-02 05:44
Thank you for the fix @sis0k0 .

On mac, the app.css was not bundled because vendor.js wasn't updated, it was fixed after running "./node_modules/.bin/update-ns-webpack --configs --deps" from [this](https://www.nativescript.org/blog/nativescript-webpack-0.9.0-what-changed-and-how-to-upgrade) guide.

Now as @berchik  mentioned, only --env.aot is failing.

**Comment by AmithRamesh** [comment] 2018-01-02 08:54
Referring #386 for --env.aot issue. It works.

**Closed** 2018-01-02 13:12 UTC
Labels: bug, Windows
