### ISSUE TITLE
Hot Module Replacement  (HMR) not working correctly, not reflecting   changes in component class file 

### ISSUE THREAD

**Issue by acharyaks90** [NativeScript/nativescript-dev-webpack#1060] opened 2019-09-24 09:45 UTC
**Environment**
 - CLI: 6.1.2
 - Cross-platform modules:  6.0.0
 - NativeScript-Angular: 8.2.1
 - Angular: 8.2.0 
 - Android 
**(HMR) not working correctly**
in debug/run mode any change in component class code not updating app refresh with file update change detection but not update code. But with --no-hmr its works perfectly fine.  

**Expected behavior**
tns debug android  should work as tns debug android --no-hmr

**Comment by Fatme** [comment] 2019-10-03 07:40
Hey guys,

We've investigated the problem and were able to reproduce the issue using the following steps:
1. `tns create newNgAapp` - select Angular, Sidedrawer
2. `tns run ios`
3. Make a change inside `search.component.html` (or `search.component.ts`)

The following text is printed on the console:
```
CONSOLE INFO file:///app/vendor.js:80079:36: HMR: Checking for updates to the bundle with hmr hash a99b4167b83a7f4aab8b.
CONSOLE INFO file:///app/vendor.js:80079:36: HMR: No Modules Updated.
```
4. Navigate to the `search` page on device

Expected: The changes should be applied on device
Actual: No changes are applied on device

5. If you make a next change inside `search` component, the change will be applied on device.

Can you confirm that you hit the same issue on your side? If this is not the case, can you describe the exact steps you're executing, so we can reproduce the issue on our side? It'll be appreciated if you can send us a demo project demonstrating the behavior.

**Comment by edrick27** [comment] 2019-10-07 01:03
hot reload don't work and TNS 6

**Comment by nkishor-nsf** [comment] 2019-10-07 04:37
I am trying...
**tns debug android should work as tns debug android --no-hmr**

**Comment by nkishor-nsf** [comment] 2019-10-07 04:38
I am facing same issue on TNS 6

**Comment by Fatme** [comment] 2019-10-09 06:30
Hey guys,

> @nkishor-nsf :  I am facing same issue on TNS 6

We described [here](https://github.com/NativeScript/nativescript-dev-webpack/issues/1060#issuecomment-537827427) how we were able to reproduce the error. It seems as a minor issue as it happens only on first navigation to a lazy loaded route. Most probably it is not the same problem you faced. So, we need more information in order to help you. Without giving us the exact steps or demo project demonstrating the problem, we cannot investigate it further.

**Comment by Ianc22** [comment] 2019-12-05 20:33
bump!

**Comment by DimitarTachev** [comment] 2019-12-06 06:52
@Ian22, 

As @Fatme has already mentioned, we are not able to reproduce the issue and we are not able to investigate it further. Could you please provide us the exact dependencies' versions and some steps for reproducing the issue?

**Comment by mhmeluskey** [comment] 2019-12-13 14:07
Hi @DimitarTachev 

I am having the same problem for my nativescript app using v 6.1.0. on a mac. I have a project that used to work fine but all of a sudden the HMR stopped working for a specific project. The hot reload on this project still works for other projects on my mac and my co workers (all non mac users) are still able to have this project working on their computers. I know thats really vague but if i send you the dependencies would you be able to look into it.

**Comment by DimitarTachev** [comment] 2019-12-13 14:28
@mhmeluskey,

This is a specific issue for updating lazy modules in Angular apps. I suggest you log another issue following the issue template. Also, the logs from `tns run <platform> --log trace` will be helpful.

P.S. Before logging the issue, please update the NativeScript CLI and the `nativescript-dev-webpack` plugin (along with your webpack.config.js file) to the latest versions. You could even check their `rc` version as we are currently preparing the 6.3.0 release and the issue could be already fixed. (`npm i nativescript@rc -g`, `npm i nativescript-dev-webpack@rc`, `./node_modules/.bin/update-ns-webpack --configs`).

**Comment by mhmeluskey** [comment] 2019-12-13 15:49
@DimitarTachev running npm i nativescript@rc -g, npm i nativescript-dev-webpack@rc, seems to have fixed my problem. Thank you for your help.

**Comment by timdoege** [comment] 2019-12-13 20:10
HMR also stopped working suddenly on my Mac (I'm on NS 6.1 + Angular 8.2). Upgrading `nativescript-dev-webpack` seems to fix this.

**Comment by DimitarTachev** [comment] 2019-12-16 06:52
I'm closing this issue as it's not related to the hot updates in Angular lazy routes anymore. For further HMR related issues, please log a new one following the issue template.

**Closed by DimitarTachev** 2019-12-16 06:52 UTC
Labels: bug, needs more info

**Comment by fgutteridge** [comment] 2019-12-20 20:37
For anyone still experiencing this issue, updating `nativescript-dev-webpack` to v1.3.0 (as @DimitarTachev and @timdoege shared) does indeed fix this issue.

**Comment by DimitarTachev** [comment] 2019-12-21 19:29
@fgutteridge, as the recent comments are not related to the initial issue, please follow the issue template and open a new issue with steps to reproduce.
