### ISSUE TITLE
Error  nativescript-dev-webpack installation

### ISSUE THREAD

**Issue by anexbm** [NativeScript/nativescript-dev-webpack#425] opened 2018-01-26 16:44 UTC
i need help
When I run  : tns android --bundle
--------------------------------------
1. tns create app-webpack --ng
 2. cd app-webpack
 3. npm install --save-dev nativescript-dev-webpack
 4. npm install
 5. tun android --bundle

tns run android --bundle

Support for Node.js 9.2.1 is not verified. This CLI might not install or run properly.
Searching for devices...
Executing before-prepare hook from D:\Training\nativeScript\app-webpack\hooks\before-prepare\nativescript-dev-typescript.js
Preparing project...
Successfully prepared plugin nativescript-angular for android.
Successfully prepared plugin nativescript-theme-core for android.
Successfully prepared plugin tns-core-modules for android.
Successfully prepared plugin nativescript-intl for android.
Successfully prepared plugin tns-core-modules-widgets for android.
Project successfully prepared (Android)
Executing after-prepare hook from D:\Training\nativeScript\app-webpack\hooks\after-prepare\nativescript-dev-webpack.js
Building project...
Gradle build...
         + applying user-defined configuration from D:\Training\nativeScript\app-webpack\app\App_Resources\Android\app.gradle
         + creating include.gradle for plugin D:\Training\nativeScript\app-webpack\node_modules\tns-core-modules-widgets
         + applying plugin configuration from D:\Training\nativeScript\app-webpack\platforms\android\build\configurations\tns-core-modules-widgets\include.gradle
         + adding nativescript runtime package dependency: nativescript-optimized
         + adding aar plugin dependency: D:\Training\nativeScript\app-webpack\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Running full build

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\Training\nativeScript\app-webpack\platforms\android\build-tools\android-static-binding-generator\build.gradle' line: 276

* What went wrong:
Execution failed for task ':asbg:generateBindings'.
> No D:\Training\nativeScript\app-webpack\platforms\android\build-tools\android-static-binding-generator/bindings.txt was found after runAstParser task was ran! Check to see if there are any .js files inside D:\Training\nativeScript\app-webpack\platforms\android\src\main\assets\app

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
Command gradlew.bat failed with exit code 1
--------------------------------------------------------------------------------
-----------------------------------Package.json-----------------------------
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "org.nativescript.appwebpack",
    "tns-android": {
      "version": "3.3.1"
    }
  },
  "dependencies": {
    "@angular/animations": "~4.4.1",
    "@angular/common": "~4.4.1",
    "@angular/compiler": "~4.4.1",
    "@angular/core": "~4.4.1",
    "@angular/forms": "~4.4.1",
    "@angular/http": "~4.4.1",
    "@angular/platform-browser": "~4.4.1",
    "@angular/router": "~4.4.1",
    "nativescript-angular": "~4.4.0",
    "nativescript-theme-core": "~1.0.2",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.4.2",
    "tns-core-modules": "^3.4.0",
    "zone.js": "~0.8.2"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~4.4.1",
    "@ngtools/webpack": "~1.9.1",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "copy-webpack-plugin": "~4.3.0",
    "css-loader": "~0.28.7",
    "extract-text-webpack-plugin": "~3.0.2",
    "lazy": "1.0.11",
    "nativescript-dev-typescript": "~0.5.0",
    "nativescript-dev-webpack": "^0.9.1",
    "nativescript-worker-loader": "~0.8.1",
    "raw-loader": "~0.5.1",
    "resolve-url-loader": "~2.2.1",
    "typescript": "~2.4.2",
    "uglifyjs-webpack-plugin": "~1.1.6",
    "webpack": "~3.10.0",
    "webpack-bundle-analyzer": "^2.9.1",
    "webpack-sources": "~1.1.0"
  }
}

**Comment by sis0k0** [comment] 2018-01-26 22:50
Seems like a duplicate of #408. Please, take a look at this comment: https://github.com/NativeScript/nativescript-dev-webpack/issues/408#issuecomment-360925466. The newly created app has old versions of the nativescript dependencies (3.3.0 and 4.4 for angular), because your global installation of the nativescript CLI is 3.3.0. If you update to 3.4.0 and create a new app with `tns create`, you'll have the latest bits :)

**Closed by sis0k0** 2018-01-26 22:50 UTC
