### ISSUE TITLE
Absolute path is not resolved in  v0.14.2 when extending activity

### ISSUE THREAD

**Issue by RoyiNamir** [NativeScript/nativescript-dev-webpack#592] opened 2018-07-02 13:56 UTC
Even after using the latest merged version : 
```
"nativescript-dev-webpack": "^0.14.2",
```
  - Which include this merged [**fix (_absolute paths on Windows_)**](https://github.com/NativeScript/nativescript-dev-webpack/pull/578) - It seems that problem still exists[ when extending activity](https://gist.github.com/RoyiNamir/0b503d69448e1e6cb0fa74f3f2481d62).

Using this command `tns build android --bundle`

**Works Good:** 
```
 const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        "./activity.android.ts"
    ];
```

**But there's an error with this :** 
```
 const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "app/activity.android.ts")

    ];
```

>Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:C:\r\a\platforms\android\app\src\main\java\org\myApp\MainActivity.java Class: org.myApp.MainActivity
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:78)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:48)

>FAILURE: Build failed with an exception.

>* What went wrong:
Execution failed for task ':app:runSbg'.

![image](https://user-images.githubusercontent.com/2842123/42167820-d766713a-7e17-11e8-8210-0f38e607b9e1.png)

(After `tns platform remove android && tns platform add android` - many times).

[**Here is a Sample empty project which shows the problem**  ](https://ufile.io/dlt93)

Related info : 

```
Windows 10 
C:\r\a>tns info
√ Getting NativeScript components versions information...
√ Component nativescript has 4.1.2 version and is up to date.
√ Component tns-core-modules has 4.1.0 version and is up to date.
√ Component tns-android has 4.1.3 version and is up to date.
‼ Update available for component tns-ios. Your current version is 4.1.0 and the latest available version is 4.1.1.
```

[package.json](https://gist.github.com/RoyiNamir/5cc7b0e22ca015fbe3b16eafeeee94bc)

**Comment by NickIliev** [comment] 2018-07-02 15:08
@RoyiNamir the error indicates a different error that is not related to the paths in Windows. 
I am using[ this POC application](https://github.com/NativeScript/sample-android-background-services) to bundle on Windows and the bundling is successful on my side - the application is using extended activity and custom background services files. Here [are the paths ](https://github.com/NativeScript/sample-android-background-services/blob/master/webpack.config.js#L17-L18)in the webpack.config.js

In your case, the static binding generation has failed for some reason. I would suggest reseting your project with the following steps.
```
// store the added lines of code for your webpack config.js and delete all of the below
rm -rf node_modules platforms hooks webpack.config.js 

npm i
// add the extended activity to the newly generated webpack.config.js
tns platform add android
tns build android --bundle
tns run android --bundle
```

Please let me know if you have a specific scenario or code invloved to reproduce your error.

**Comment by RoyiNamir** [comment] 2018-07-02 15:29
@NickIliev Hi Nick. Code involved was added ^ ([ here it is](https://ufile.io/dlt93) )

**Exactly(!) the steps you said ^**

**Before delete :** 

 
![image](https://user-images.githubusercontent.com/2842123/42171943-4e88f278-7e23-11e8-9e6d-5e585aaae3a0.png)

**After delete :** 

 
![image](https://user-images.githubusercontent.com/2842123/42172532-ee7ce02c-7e24-11e8-996e-95809e808fbe.png)



**Npm install :** 
 
![image](https://user-images.githubusercontent.com/2842123/42172141-dab59bde-7e23-11e8-906b-3b2f8f0a1736.png)

**Adding the activity :** 
```
   const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        resolve(__dirname, "app/activity.android.ts")
        
    ];
```
**tns platform add android :** 

![image](https://user-images.githubusercontent.com/2842123/42172253-28949828-7e24-11e8-905d-28b634fb544e.png)

**tns build android --bundle**
Getting error ( same as I mentioned) : 

>Webpack compilation complete.
Project successfully prepared (android)
Executing after-prepare hook from C:\r\a\hooks\after-prepare\nativescript-dev-webpack.js
Building project...
Gradle build...
         + setting applicationId
         + applying user-defined configuration from C:\r\a\app\App_Resources\Android\app.gradle
         + adding nativescript runtime package dependency: nativescript-optimized-with-inspector
         + adding aar plugin dependency: C:\r\a\node_modules\tns-core-modules-widgets\platforms\android\widgets-release.aar
Warning: there already is an extend called org.myApp.MainActivity.
Warning: The static binding generator will generate extend from:vendor.js implementation
Exception in thread "main" java.io.IOException: File already exists. This may lead to undesired behavior.
Please change the name of one of the extended classes.
File:C:\r\a\platforms\android\app\src\main\java\org\myApp\MainActivity.java Class: org.myApp.MainActivity
        at org.nativescript.staticbindinggenerator.Generator.writeBindings(Generator.java:78)
        at org.nativescript.staticbindinggenerator.Main.main(Main.java:48)

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:runSbg'.
> Process 'command 'C:\Program Files\Java\jdk1.8.0_172\bin\java.exe'' finished with non-zero exit value 1


![image](https://user-images.githubusercontent.com/2842123/42172384-82627924-7e24-11e8-9f33-ae617082a050.png)


# HOWEVER - Changing it to :

```
  const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        "./activity.android.ts"

    ];
```

**running - tns build android --bundle ( after tns platform remove/add)**

Does work : 


![image](https://user-images.githubusercontent.com/2842123/42172828-d993762a-7e25-11e8-803a-12899ae78a2e.png)

**Comment by NickIliev** [comment] 2018-07-03 11:32
@RoyiNamir the issue seems to be caused by an `export` and `import` of a variable from your extended activity. There are two possible workaround for your case

**Workaround 1** (wont work on iOS as it will require to import a platform-specific file)

```
import { AndroidOnRouteToURL } from "./activity";
```
to
```
import { AndroidOnRouteToURL } from "./activity.android";
```
in app.component.ts

**Workaround 2** 

As @RoyiNamir has pointed out the solution is to use a relative path (in `webpack.config.js`) for the extend activity.
```
const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
        "./activity.android.ts"

    ];
```

The above will work on both Android and IOS but will disable build on MAC with snapshot (`--env,snapshot`). This won't affect Windows builds. Another thing to notice is that in such cases there will be two files created and the extended activity will be in the `bundle` and not in the `vendor`.

**Closed** 2018-07-03 11:33 UTC
Labels: os: android
