### ISSUE TITLE
JS: Error: Css styling failed: Error: undefined:1:16: missing '{'

### ISSUE THREAD

**Issue by syntiro** [NativeScript/nativescript-dev-webpack#754] opened 2018-12-29 23:38 UTC
**Environment**
 - CLI: 5.1.0
 - core modules: 5.1.1
 - Android Runtime: 5.1.0
 - iOS Runtime:  5.1.0
 - Node: 10.4.1

**Description**
Android and Ios app runtime error "JS: Error: Css styling failed: Error: undefined:1:16: missing '{'" when using bundle option to build and run the app.

I've followed the instructions here for using webpack to bundle code 
https://docs.nativescript.org/performance-optimizations/bundling-with-webpack
and the same error always appears. I have read where this issue occurs when a css file is empty and  when I look into the apk files it looks nothing like the non bundled solution. There's no css files at all in there and only a few js files along with the vendor and bundle js files. My config needs work I guess and maybe that's where I need some guidance to understand more the relationship between the config and my project structure.

JS: Error: Css styling failed: Error: undefined:1:16: missing '{'
System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: 
System.err: Error calling module function 
System.err: Error calling module function 
System.err: Error: Application is already started.
System.err: File: "file:///data/data/package.id/files/app/vendor.js, line: 103872, column: 8
System.err: StackTrace: 
System.err: 	Frame: function:'ZoneAwareError', file:'file:///data/data/package.id/files/app/vendor.js', line: 82935, column: 33
System.err: 	Frame: function:'start', file:'file:///data/data/package.id/files/app/vendor.js', line: 103872, column: 15
System.err: 	Frame: function:'run', file:'file:///data/data/package.id/files/app/vendor.js', line: 103888, column: 5
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/platform-common.js.NativeScriptPlatformRef.bootstrapNativeScriptApp', file:'file:///data/data/package.id/files/app/vendor.js', line: 78957, column: 23
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/platform-common.js.NativeScriptPlatformRef.bootstrapApp', file:'file:///data/data/package.id/files/app/vendor.js', line: 78891, column: 14
System.err: 	Frame: function:'push.../node_modules/nativescript-angular/platform-common.js.NativeScriptPlatformRef.bootstrapModule', file:'file:///data/data/package.id/files/app/vendor.js', line: 78880, column: 14
System.err: 	Frame: function:'', file:'file:///data/data/package.id/files/app/bundle.js', line: 1201, column: 101
System.err: 	Frame: function:'./main.ts', file:'file:///data/data/package.id/files/app/bundle.js', line: 1206, column: 30
System.err: 	Frame: function:'__webpack_require__', file:'file:///data/data/package.id/files/app/bundle.js', line: 76, column: 30
System.err: 	Frame: function:'checkDeferredModules', file:'file:///data/data/package.id/files/app/bundle.js', line: 45, column: 23
System.err: 	Frame: function:'module.exports.../$$_lazy_route_resource lazy recursive.map../modules/history/history.module', file:'file:///data/data/package.id/files/app/bundle.js', line: 166, column: 18
System.err: 	Frame: function:'', file:'file:///data/data/package.id/files/app/bundle.js', line: 169, column: 10
System.err: 	Frame: function:'require', file:'', line: 1, column: 266
System.err: 	Frame: function:'', file:'file:///data/data/package.id/files/app/starter.js', line: 2, column: 1
System.err: 	Frame: function:'require', file:'', line: 1, column: 266

**To Reproduce**
```
tns run android|ios --bundle
```
**package.json **
```
{
  "description": "NativeScript Application",
  "license": "SEE LICENSE IN <your-license-filename>",
  "readme": "NativeScript Application",
  "repository": "<fill-your-repository-here>",
  "nativescript": {
    "id": "package.id",
    "tns-android": {
      "version": "5.1.0"
    },
    "tns-ios": {
      "version": "5.1.0"
    }
  },
  "scripts": {
    "e2e": "tsc -p e2e && mocha --opts ./e2e/config/mocha.opts",
    "e2e-watch": "tsc -p e2e --watch",
    "dev": "tns run android --bundle --env.name=development",
    "prod": "tns build android --bundle --env.name=production --env.uglify"
  },
  "dependencies": {
    "@angular/animations": "7.1.4",
    "@angular/common": "7.1.4",
    "@angular/compiler": "7.1.4",
    "@angular/core": "7.1.4",
    "@angular/forms": "7.1.4",
    "@angular/http": "7.1.4",
    "@angular/platform-browser": "7.1.4",
    "@angular/platform-browser-dynamic": "7.1.4",
    "@angular/router": "7.1.4",
    "@types/validator": "9.4.1",
    "@types/xml-parser": "^1.2.29",
    "fast-xml-parser": "3.12.5",
    "nativescript-angular": "6.1.0",
    "nativescript-checkbox": "3.0.3",
    "nativescript-https": "^1.0.1",
    "nativescript-image-cache": "1.1.6",
    "nativescript-localize": "3.0.6",
    "nativescript-secure-storage": "^2.3.0",
    "nativescript-sqlite": "2.2.3",
    "nativescript-sqlite-commercial": "file:nativescript-sqlite-commercial-1.2.0.tgz",
    "nativescript-sqlite-encrypted": "file:nativescript-sqlite-encrypted-1.2.1.tgz",
    "nativescript-theme-core": "1.0.4",
    "nativescript-ui-listview": "3.6.1",
    "nativescript-videoplayer": "4.2.0",
    "nativescript-youtube-parser": "1.1.0",
    "reflect-metadata": "0.1.12",
    "rxjs": "6.3.2",
    "tns-core-modules": "^5.1.1",
    "typescript-map": "0.0.6",
    "zone.js": "0.8.26"
  },
  "devDependencies": {
    "@angular/compiler-cli": "~6.1.0",
    "@ngtools/webpack": "~6.2.0",
    "@types/chai": "4.1.4",
    "@types/mocha": "2.2.41",
    "@types/node": "10.9.4",
    "babel-traverse": "6.4.5",
    "babel-types": "6.4.5",
    "babylon": "6.4.5",
    "lazy": "1.0.11",
    "mobile-devices-controller": "2.8.2",
    "nativescript-dev-appium": "3.3.0",
    "nativescript-dev-sass": "1.6.0",
    "nativescript-dev-typescript": "0.7.2",
    "nativescript-dev-webpack": "^0.16.3",
    "node-sass": "^4.11.0",
    "tslint": "5.11.0",
    "typescript": "2.9.1",
    "uglifyjs-webpack-plugin": "^2.1.1",
    "webpack": "^4.28.3",
    "webpack-obfuscator": "^0.18.0"
  }
}

```

**webpack.config.js **
```
const { join, relative, resolve, sep } = require("path");

const webpack = require("webpack");
const nsWebpack = require("nativescript-dev-webpack");
const nativescriptTarget = require("nativescript-dev-webpack/nativescript-target");
const { nsReplaceBootstrap } = require("nativescript-dev-webpack/transformers/ns-replace-bootstrap");
const CleanWebpackPlugin = require("clean-webpack-plugin");
const CopyWebpackPlugin = require("copy-webpack-plugin");
const { BundleAnalyzerPlugin } = require("webpack-bundle-analyzer");
const { NativeScriptWorkerPlugin } = require("nativescript-worker-loader/NativeScriptWorkerPlugin");
const UglifyJsPlugin = require("uglifyjs-webpack-plugin");
const { AngularCompilerPlugin } = require("@ngtools/webpack");

module.exports = env => {
    // Add your custom Activities, Services and other Android app components here.
    const appComponents = [
        "tns-core-modules/ui/frame",
        "tns-core-modules/ui/frame/activity",
    ];

    const platform = env && (env.android && "android" || env.ios && "ios");
    if (!platform) {
        throw new Error("You need to provide a target platform!");
    }

    const projectRoot = __dirname;

    // Default destination inside platforms/<platform>/...
    const dist = resolve(projectRoot, nsWebpack.getAppPath(platform, projectRoot));
    const appResourcesPlatformDir = platform === "android" ? "Android" : "iOS";

    const {
        // The 'appPath' and 'appResourcesPath' values are fetched from
        // the nsconfig.json configuration file
        // when bundling with `tns run android|ios --bundle`.
        appPath = "app",
        appResourcesPath = "app/App_Resources",

        // You can provide the following flags when running 'tns run android|ios'
        aot, // --env.aot
        snapshot, // --env.snapshot
        uglify, // --env.uglify
        report, // --env.report
        sourceMap, // --env.sourceMap
    } = env;

    const appFullPath = resolve(projectRoot, appPath);
    const appResourcesFullPath = resolve(projectRoot, appResourcesPath);

    const entryModule = `${nsWebpack.getEntryModule(appFullPath)}.ts`;
    const entryPath = `.${sep}${entryModule}`;

    const ngCompilerPlugin = new AngularCompilerPlugin({
        hostReplacementPaths: nsWebpack.getResolver([platform, "tns"]),
        platformTransformers: aot ? [nsReplaceBootstrap(() => ngCompilerPlugin)] : null,
        mainPath: resolve(appPath, entryModule),
        tsConfigPath: join(__dirname, "tsconfig.tns.json"),
        skipCodeGeneration: !aot,
        sourceMap: !!sourceMap,
    });

    const config = {
        mode: uglify ? "production" : "development",
        context: appFullPath,
        watchOptions: {
            ignored: [
                appResourcesFullPath,
                // Don't watch hidden files
                "**/.*",
            ]
        },
        target: nativescriptTarget,
        entry: {
            bundle: entryPath,
        },
        output: {
            pathinfo: false,
            path: dist,
            libraryTarget: "commonjs2",
            filename: "[name].js",
            globalObject: "global",
        },
        resolve: {
            extensions: [".ts", ".js", ".scss", ".css"],
            // Resolve {N} system modules from tns-core-modules
            modules: [
                resolve(__dirname, "node_modules/tns-core-modules"),
                resolve(__dirname, "node_modules"),
                "node_modules/tns-core-modules",
                "node_modules",
            ],
            alias: {
                '~': appFullPath
            },
            symlinks: true
        },
        resolveLoader: {
            symlinks: false
        },
        node: {
            // Disable node shims that conflict with NativeScript
            "http": false,
            "timers": false,
            "setImmediate": false,
            "fs": "empty",
            "__dirname": false,
        },
        devtool: sourceMap ? "inline-source-map" : "none",
        optimization: {
            splitChunks: {
                cacheGroups: {
                    vendor: {
                        name: "vendor",
                        chunks: "all",
                        test: (module, chunks) => {
                            const moduleName = module.nameForCondition ? module.nameForCondition() : '';
                            return /[\\/]node_modules[\\/]/.test(moduleName) ||
                                appComponents.some(comp => comp === moduleName);
                        },
                        enforce: true,
                    },
                }
            },
            minimize: !!uglify,
            minimizer: [
                new UglifyJsPlugin({
                    uglifyOptions: {
                        parallel: true,
                        cache: true,
                        output: {
                            comments: false,
                        },
                        compress: {
                            // The Android SBG has problems parsing the output
                            // when these options are enabled
                            'collapse_vars': platform !== "android",
                            sequences: platform !== "android",
                        }
                    }
                })
            ],
        },
        module: {
            rules: [
                {
                    test: new RegExp(entryPath),
                    use: [
                        // Require all Android app components
                        platform === "android" && {
                            loader: "nativescript-dev-webpack/android-app-components-loader",
                            options: { modules: appComponents }
                        },

                        {
                            loader: "nativescript-dev-webpack/bundle-config-loader",
                            options: {
                                angular: true,
                                loadCss: !snapshot, // load the application css if in debug mode
                            }
                        },
                    ].filter(loader => !!loader)
                },

                { test: /\.html$|\.xml$/, use: "raw-loader" },

                // tns-core-modules reads the app.css and its imports using css-loader
                {
                    test: /[\/|\\]app\.css$/,
                    use: {
                        loader: "css-loader",
                        options: { minimize: false, url: false },
                    }
                },
                {
                    test: /[\/|\\]app\.scss$/,
                    use: [
                        { loader: "css-loader", options: { minimize: false, url: false } },
                        "sass-loader"
                    ]
                },

                // Angular components reference css files and their imports using raw-loader
                { test: /\.css$/, exclude: /[\/|\\]app\.css$/, use: "raw-loader" },
                { test: /\.scss$/, exclude: /[\/|\\]app\.scss$/, use: ["raw-loader", "resolve-url-loader", "sass-loader"] },

                {
                    test: /(?:\.ngfactory\.js|\.ngstyle\.js|\.ts)$/,
                    use: [
                        "nativescript-dev-webpack/moduleid-compat-loader",
                        "@ngtools/webpack",
                    ]
                },

                // Mark files inside `@angular/core` as using SystemJS style dynamic imports.
                // Removing this will cause deprecation warnings to appear.
                {
                    test: /[\/\\]@angular[\/\\]core[\/\\].+\.js$/,
                    parser: { system: true },
                },
            ],
        },
        plugins: [
            // Define useful constants like TNS_WEBPACK
            new webpack.DefinePlugin({
                "global.TNS_WEBPACK": "true",
                "process": undefined,
            }),
            // Remove all files from the out dir.
            new CleanWebpackPlugin([`${dist}/**/*`]),
            // Copy native app resources to out dir.
            new CopyWebpackPlugin([
                {
                    from: `${appResourcesFullPath}/${appResourcesPlatformDir}`,
                    to: `${dist}/App_Resources/${appResourcesPlatformDir}`,
                    context: projectRoot
                },
            ]),
            // Copy assets to out dir. Add your own globs as needed.
            new CopyWebpackPlugin([
                { from: "fonts/**" },
                { from: "**/*.jpg" },
                { from: "**/*.png" },
            ], { ignore: [`${relative(appPath, appResourcesFullPath)}/**`] }),
            // Generate a bundle starter script and activate it in package.json
            new nsWebpack.GenerateBundleStarterPlugin([
                "./vendor",
                "./bundle",
            ]),
            // For instructions on how to set up workers with webpack
            // check out https://github.com/nativescript/worker-loader
            new NativeScriptWorkerPlugin(),
            ngCompilerPlugin,
            // Does IPC communication with the {N} CLI to notify events when running in watch mode.
            new nsWebpack.WatchStateLoggerPlugin(),
        ],
    };


    if (report) {
        // Generate report files for bundles content
        config.plugins.push(new BundleAnalyzerPlugin({
            analyzerMode: "static",
            openAnalyzer: false,
            generateStatsFile: true,
            reportFilename: resolve(projectRoot, "report", `report.html`),
            statsFilename: resolve(projectRoot, "report", `stats.json`),
        }));
    }

    if (snapshot) {
        config.plugins.push(new nsWebpack.NativeScriptSnapshotPlugin({
            chunk: "vendor",
            angular: true,
            requireModules: [
                "reflect-metadata",
                "@angular/platform-browser",
                "@angular/core",
                "@angular/common",
                "@angular/router",
                "nativescript-angular/platform-static",
                "nativescript-angular/router",
            ],
            projectRoot,
            webpackConfig: config,
        }));
    }

    return config;
};
```

**Comment by NickIliev** [comment] 2019-01-07 08:05
@syntiro your dependencies are outdated - follow [the upgrade instructions described here ]("nativescript-dev-webpack": "^0.16.3",)to update to the latest versions of all Angular and Webpack related dependencies and developer dependencies.

**Comment by NickIliev** [comment] 2019-01-10 06:50
@syntiro we were able to reproduce the issue with the latest versions as well - I will post any related information once we have more insights.

**Comment by vchimev** [comment] 2019-01-16 11:17
Hey @syntiro,

There are two separate issues here based on the log provided:

1. The `JS: Error: Css styling failed: Error: undefined:1:16: missing '{'` error related to application styling. I was able to reproduce it and it is not the reason for the application to crash.
2. The `System.err: java.lang.RuntimeException: Unable to create application com.tns.NativeScriptApplication: com.tns.NativeScriptException: ` exception. Could you please isolate this in a sample repo?

In regards with bundling, the `vendor.js` file conatins the `node_modules` and the `bundle.js` file contains the application modules, including the CSS files.

**Comment by NickIliev** [comment] 2019-02-19 11:02
@syntiro the issue was reproducible when there were no styles in the global app.css (or `app.scss`) - however, with the latest version of nativescript-dev-webpack, I am not able to reproduce this one and everything seem to work as expected.

Closing as resolved but please do let me know if I am missing some step needed to reproduce this one (used t[his test app](https://github.com/NickIliev/NS-Issues-2019-I/tree/master/nativescript-dev-webpack/issue-754)).

**Closed by NickIliev** 2019-02-19 11:02 UTC
Labels: bug

**Comment by syntiro** [comment] 2019-07-31 04:49
In the end the issue was caused by an old app.js in the project which had a reference to a bundle-config that didn't exist and a few other configurations. I just deleted the app.js and the bundle build was back working.
